[package]
name = "aplang"
version = "0.0.1"
authors = ["Patrick Unick <dev_storm@winux.com>"]
edition = "2021"
description = "A language designed for AP Computer Science Principles students"
license = "GPL-3.0-or-later"
keywords = ["language", "lang", "cli", "ap", "interpreter"]
repository = "https://github.com/snowfoxsh/aplang"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"
num-derive = "0.4.0"
num-traits = "0.2.16"
expect-test = "1.4.1"
rustyline = "12.0.0"
clap = { version = "4.3.24", features = ["cargo", "derive"] }
mapro = "0.1.1"

[features]
c_syntax = []