[package]
name = "aplang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.13.0"
rowan = "0.15.11"
num-derive = "0.4.0"
num-traits = "0.2.16"