[package]
name = "aplang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapro = "0.1.1"
ariadne = "0.4.0"
