[package]
name = "aplang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mapro = "0.1.1"
miette = { version = "7.2.0", features = ["fancy"] }
#miette = { version = "7.2.0" }
owo-colors = "4.0.0"
