use std::fs;
use clap::{Parser as ClapParser, ValueEnum};
use logos::Logos;
use crate::debug::LangDebug;
use crate::lexer::debug::{DebugSyntaxKind, Echo};
use crate::parser::debug::DebugParser;
use crate::repl::run_repl;

mod repl;
mod run;
mod lexer;
mod parser;
mod debug;

#[derive(ValueEnum, Debug, Clone, Copy)]
enum DebugMode {
    /// Print expression output
    None,
    /// Print AST generated by parser
    Parser,
    /// Print Tokens generated by the Lexer
    Syntax,
    /// Echo back your program
    Echo,
}

#[derive(ClapParser, Debug)]
#[clap(author, version, about="A language designed for AP Computer Science Principles students")]
struct Cli {
    /// a file that you would like run, leave this out to run the REPL
    file: Option<String>,

    #[arg(short='d', long, default_value="none", value_name="MODE", value_enum)]
    debug: DebugMode,

    #[arg(short='e', long, value_name="CODE")]
    eval: Option<String>,
}

fn main() {
    let cli: Cli = Cli::parse();

    let run_code = match cli.debug {
        DebugMode::None => run::run,
        DebugMode::Parser => DebugParser::debug,
        DebugMode::Syntax => DebugSyntaxKind::debug,
        DebugMode::Echo => Echo::debug,
    };

    if let Some(file_path) = cli.file {
        let code = fs::read_to_string(file_path.clone())
            .unwrap_or_else(|_| panic!("could not read file: {}", file_path));

        run_code(code);
        return;
    }

    if let Some(code) = cli.eval {
        run_code(code);
        return;
    }


    run_repl().unwrap()
}