name: Build Artifacts

on:
  workflow_dispatch:
  push:
    tags:
    - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  # build base and upload as an artifact
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --release --bin aplang

    - name: Upload build artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: windows-aplang-binary
        path: target/release/aplang.exe
