name: Install Apple Certificates

on:
  push:
    paths:
      - .github/workflows/install-apple-cert.yml
  workflow_dispatch:

jobs:
  install-certs:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode and install Apple certificates
        env:
          APPLICATION_CERT_BASE64: ${{ secrets.APPLE_APPLICATION_CERT }}
          INSTALLER_CERT_BASE64: ${{ secrets.APPLE_INSTALLER_CERT }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
          TEMP_KEYCHAIN_PASSWORD: temp_password
        run: |
          echo "$APPLICATION_CERT_BASE64" | base64 --decode > application_cert.p12
          echo "$INSTALLER_CERT_BASE64" | base64 --decode > installer_cert.p12

          # Create a temporary keychain with a temporary password
          security create-keychain -p "$TEMP_KEYCHAIN_PASSWORD" temp.keychain
          security unlock-keychain -p "$TEMP_KEYCHAIN_PASSWORD" temp.keychain

          # Import certificates into the temporary keychain
          security import application_cert.p12 -k temp.keychain -P "$CERT_PASSWORD" -T /usr/bin/codesign
          security import installer_cert.p12 -k temp.keychain -P "$CERT_PASSWORD" -T /usr/bin/codesign

          # Set the key partition list with explicit unlocking
          security set-key-partition-list -S apple-tool:,apple: -s -k "$TEMP_KEYCHAIN_PASSWORD" temp.keychain

      - name: Verify certificate installation
        run: |
          security find-certificate -v -p temp.keychain
