name: Build MSIX Package

on:
  workflow_dispatch:

jobs:
  build-msix:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add Windows SDK Tools to PATH
        run: |
          echo "Adding Windows SDK to PATH"
          $env:Path += ";C:\Program Files (x86)\Windows Kits\10\bin\x64"
          echo $env:Path
      - name: Create MSIX Package
        run: |
          MakeAppx pack /d "ci\msix-package-root" /p "aplang.msix"
