name: Build MSIX Package

on:
  workflow_dispatch:

jobs:
  build-msix:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Windows SDK 
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2.4
      - name: Create MSIX Package
        run: |
          MakeAppx pack /d "ci\msix-package-root" /p "aplang.msix"
