name: Test

on:
  workflow_call:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Add Wasm32 target
      run: rustup target add wasm32-unknown-unknown
    - name: Test Build to WASM
      run: |
        RUSTFLAGS='--cfg getrandom_backend="wasm_js"' cargo build --verbose --lib --target wasm32-unknown-unknown --no-default-features --features wasm 
